### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#130]
After #121 and #129 are merged we'll have native support for overloaded labels and all major lens modules ported, two exceptions being:
- `Plated`, which is weird and perhaps belongs in a separate package optics-plated (not maintained by us) and
- `Wrapped`, which I'm not sure is needed (we'll see after we make a release).

I think we need to:
- add a couple of remaining utility functions to optics-extra,
- make sure that examples compile (with doctest),
- write a short `README.md`

and we can make an initial release. All functions have haddock documentation, documentation for "what each optic is" can be filled later I think.

**Comment by phadej** [comment]
We need a proper documentation. We have only single chance to give good first impression.

**Comment by arybczak** [comment]
As documentation is in a good state now, let's set a (soft) deadline for release to the end of May.

**Comment by arybczak** [comment]
Outstanding issues to be solved before release:

- [ ] Figure out if it's feasible to make #160 work
- [ ] Name coindex variables consistently for the sake of future code readers in #153 and merge it
- [ ] Document known limitations of sop-generated optics
- [ ] Remove `toLens` etc. (#146)
- [ ] Sort out `matching`/`isn't` placement, i.e. merge #155 
- [ ] Add function equivalents of operators in Optics.Operators.State (#162)
- [ ] Add `unsafeFiltered`

**Comment by adamgundry** [comment]
@arybczak said on #208:
> I'd skip this issue, merge outstanding PRs and actually release the damn thing ;) 

I'm sympathetic to the desire to stop letting this linger and actually ship it. I'm not aware of any remaining blockers, and we're already well past the amount of polishing necessary for an 0.1 release. :wink:

That said, I'm away on holiday from 12th-20th July, and very busy before then. I'd quite like to write a Well-Typed blog post to accompany/advertise the release, and be around to respond to any resulting feedback. So if you're happy to wait a tiny bit longer, could we aim to release in the week commencing 22nd July?

cc @phadej @kosmikus

**Comment by arybczak** [comment]
> could we aim to release in the week commencing 22nd July?

Sounds good, let's do it :tada:

**Comment by mitchellwrosen** [comment]
bump!

**Comment by arybczak** [comment]
@adamgundry if you're currently swamped, maybe it's worth adjusting the release strategy a bit, i.e. release `optics` now, make an announcement on reddit and whatnot and then (some time) later write a blog post about it? That way potentially more people will learn of existence of `optics` and it shouldn't feel forced.

**Comment by adamgundry** [comment]
@arybczak fair enough, I'm sorry for being a blocker. Yes by all means let's release and that will either force me to write a blog post quickly or not at all...

**Comment by adamgundry** [comment]
I've created candidates based on d7b60cf3c5d651115620fe166db8e291aa9e9274
* https://hackage.haskell.org/package/optics-0.1/candidate
* https://hackage.haskell.org/package/optics-core-0.1/candidate
* https://hackage.haskell.org/package/optics-extra-0.1/candidate
* https://hackage.haskell.org/package/optics-vl-0.1/candidate

**Comment by phadej** [comment]
@adamgundry did you forget `optics-th`?

**Comment by adamgundry** [comment]
> did you forget `optics-th`?

Apparently yes, good catch. I've added it and updated the relevant candidates to e0d30b28efa2e0601a114e0083715e6f3adb4ce7.
